[build]
  publish = "dist"
  command = "npm run build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#static"

[[headers]]
   for ="/sitemap_index.xml"
   [headers.values]
      Content-Type ="application/xml"
